### ISSUE TITLE
Engine is broken on Android

### ISSUE THREAD

**Issue by Raypuia** [Yozzaxia1311/MegaManLove#9]
Hiya!, when i was cloning the repo, i found the engine was totally broken on mobile.
This happens on almost any state, no gameplay, nothing works except for the titlescreen...

Tested with lastest LOVE build if you ask
![Screenshot_2020-05-09-00-08-07](https://user-images.githubusercontent.com/65057882/81463924-71908600-918b-11ea-987c-3a7640fbe821.png)

**Comment by Yozzaxia1311** [comment]
Can you describe what happens in more detail? Does anything spawn, including Mega Man? Are there any sounds?

By the way, for me, it immediately crashed because of shader issues. A recent commit disables the NES shader for mobile devices, and that seemed to fix it for me... but I don't know if it fixes your case.

**Comment by Raypuia** [comment]
I checked and now works!

**Comment by Raypuia** [comment]
It looks like there was something wrong with a core lib, in one of the commits (i think transitions.lua to be exactly) fixed the issue.

Btw now it works

**Comment by Yozzaxia1311** [comment]
Okay, thank you! I have a bad habit of assuming everything works after a big change. 😅
